# PART - 1
# Import libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf 

# Data Processing 
importing the data

In [2]:
dataset = pd.read_csv('D:/Its me/Deep Learning Udemy Course/Part 1 - Artificial Neural Networks/Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


# Encoding the categorical data

Label Encoding the 'Gender' column

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [6]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


# Spliting Dataset into Training set & Test set  

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

# Feature Scaling


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

# PART - 2

# Building the ANN
Initializing the ANN

In [11]:
ann = tf.keras.models.Sequential()

Adding the input layer and first hidden layer 

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the second hidden layer 

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

Adding the Output layer 

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# PART - 3
# Training the ANN

Compiling the ANN

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training the ANN on Training Set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 4s 2ms/step - loss: 0.5455 - accuracy: 0.7935
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4675 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4432 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4292 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4177 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4014 - accuracy: 0.7960
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3945 - accuracy: 0.7959
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3893 - accuracy: 0.7983
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3850 - accura

# PART - 4
# Mkaing the predictions and evaluting the model

Prediction for a single customer (Home Work)

Use our ANN model to predict if the customer with the following information will have leave the bank:

Geography: Frnace 
Credit Score:600
Gender:Male 
Age:40 year old
Tenure:3 years 
Balance: 60000
Number of products:2
Does this customer have credit card? Yes
Is the customer an Active Member. Yes 
Estimated Salary: $ 50000
So, should we say goodbye to the customer?

In [22]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))> 0.5)

[[False]]


Predicting the test set

In [26]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making confusion matrix 

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1537   58]
 [ 218  187]]


0.862